- name: nuxeo-kibana-apb playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: provision-nuxeo-kibana-apb
    playbook_debug: false
  vars:
    apb_action: provision
