---

- name: "Create temporary build directory"
  tempfile:
    state: directory
    suffix: key
  register: tmpdir

- name: "Set CA certificate and key file path facts"
  set_fact:
    tls_cacert_path: "{{tmpdir.path}}/tls.crt"
    tls_cakey_path: "{{tmpdir.path}}/tls.key"

- name: "Create the CA certificate and key"
  command: >
    openssl req -newkey rsa:2048 -new -x509 -days {{ certificate_validity }} -nodes
    -out {{ tls_cacert_path }} -keyout {{ tls_cakey_path }} -subj "/CN=nuxeo.mongodb.svc{{ tls_casubjectDistinguishedNameSuffix }}"

- name: "set broker objects state={{ state }}"
  include_tasks: "set_broker_object_state.yml name='ca_secret' desc='ca secret'"

- name: "Delete temporary build directory"
  file:
    path: "{{tmpdir.path}}"
    state: absent
