- name: Playbook to deprovision an ARender Rendition service
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: nuxeo-arender-rendition-apb
  vars:
    apb_action: deprovision