---
state_map:
  provision: present
  deprovision: absent
state: "{{ state_map[apb_action] }}"
# Whether we are in a cluster or not.
pod_name: "{{ lookup('env', 'POD_NAME') }}"
pod_namespace: "{{ lookup('env', 'POD_NAMESPACE') }}"
in_cluster: "{{ True if (pod_name and pod_namespace) else False }}"

name: "{{ project_name if project_name is defined else 'nuxeo-minio-' + (_apb_service_instance_id | string |truncate(5, True, '') ) }}"

secret_lookup: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits') }}"

minio_dc_lookup: "{{ lookup('openshift', kind='DeploymentConfig', namespace=namespace, resource_name=minio_dc_name) }}"
minio_route_lookup: "{{ lookup('openshift', kind='Route', namespace=namespace, resource_name=minio_route_name) }}"

# Variables to hold queries
ready_replicas_query: "[spec.replicas, status.readyReplicas]"
minio_dc_query: "{{ minio_dc_lookup | json_query(ready_replicas_query) | unique | count == 1 }}"

app_name: "{{ name }}"
minio_service_name: "{{ name }}"
minio_secret_name: "{{ name }}-credentials"
minio_config_name: "{{ name }}"
minio_dc_name: "{{ name }}"
minio_pvc_name: "{{ name }}-data"
minio_route_name: "{{ name }}"