---
- name: nuxeo-s3-apb bind
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansibleplaybookbundle.asb-modules
  - role: nuxeo-s3-apb-bind
  vars:
    apb_action: bind

