---

- name: "Update last operation"
  asb_last_operation:
    description: "0%: Starting"
  when: in_cluster

- name: "Deploy ARender rendition pool"
  include_tasks: "default.yml"
  when: _apb_plan_id == "default"

- name: "Deploy Bridge to rendition pool"
  include_tasks: "bridge.yml"
  when: _apb_plan_id == "bridge"

- name: "Update last operation"
  asb_last_operation:
    description: "100%: Cluster objects state={{ state }}"
  when: in_cluster